### ISSUE TITLE
[Trigger][CombatLog] Critical damage trigger not working.

### ISSUE THREAD

**Issue by Sattva-108** [RichSteini/WeakAuras2-TBC-2.4.3#12]
## Describe the bug

Trigger - Combat Log - Spell - Damage - Player - Critical - **not working.**

### To Reproduce

1. Create any new Weakaura
2. Make it in trigger: Combat Log - Spell - Damage - Player - Critical 
3. Try and see if it works.

**Which version of WeakAuras are you using?**

I'm using 4.0.0

### Video of bug reproduce on Stormforge TBC PTR. 

https://user-images.githubusercontent.com/74269253/224537873-9e9e41d9-d14d-4065-bea3-17efc3ca68f0.mp4

**Comment by RichSteini** [comment]
Fixed in [Fix combat log spell critical etc. suffix](https://github.com/RichSteini/WeakAuras2-TBC-2.4.3/commit/f3f913649ec03fc389765b516dd02ec6970586c1).
