### ISSUE TITLE
[Trigger] SpeedrunSplits addon confict.

### ISSUE THREAD

**Issue by Sattva-108** [RichSteini/WeakAuras2-TBC-2.4.3#13]
## Describe the bug

**Trigger - Aura - Player** - Buff - Debuff - Buff/Debuff **not working** properly if you have SpeedrunSplits addon insalled.
Link to [SpeedrunSplits by Zarant.](https://mega.nz/file/GJNWSDwC#-64PNQ1PXBZPvXtojxXOPTm76if9ky6rDs7S5aprNpM)

### To Reproduce

1. Install **SpeedrunSplits** backport by Zarant.
2. Create icon Weakaura
3. Make it in trigger: Aura - Player - Buff - Type spell name (e.g. Mark of the wild) - Select on bottom Aura Missing.
4. Buff yourself with Mark of the Wild. (the icon will disappear) 
5. Open and close Weakauras window, and you will see icon again is popped.

**Which version of WeakAuras are you using?**

I'm using 4.0.0

### Video of bug reproduce on Stormforge TBC PTR. 

https://user-images.githubusercontent.com/74269253/224690029-25dc4031-f80a-4652-9613-ebba66ad99ba.mp4

**Comment by Sattva-108** [comment]
## UPDATE - 1 
Trigger works perfectly if buff tracked on target.

**Comment by Sattva-108** [comment]
## UPDATE - 2
So i have reduced code of SpeedrunSplits.lua as much as i could, so that Weakauras Trigger Bug is still present.
```
function SpeedrunSplits_OnLoad()
	this:RegisterEvent("ADDON_LOADED")
	this:RegisterEvent("PLAYER_LEVEL_UP")
	this:RegisterEvent("PLAYER_LOGIN")
end



local f1 = CreateFrame("Frame",nil,f2)
f1:SetWidth(1) 
f1:SetHeight(1) 
f1:SetAlpha(1);
f1:SetPoint("TOPLEFT",5,-120)



 
local f2 = CreateFrame("Frame",nil,f1)
f2:SetWidth(1) 
f2:SetHeight(1) 
f2:SetAlpha(1);
f2:SetPoint("TOPLEFT",120,0) 
```



 








On video you can see errors i have been getting after reducing lua code.

https://user-images.githubusercontent.com/74269253/224708225-00849493-d822-4989-a255-5b1f73a92d4f.mp4


My assumption is that - it's not the .lua file problem, but SpeedrunSplits.xml
Because [original SpeedrunSplits](https://www.curseforge.com/wow/addons/speedrunsplits) doesn't have a **.xml** file.
```
<Ui xmlns="http://www.blizzard.com/wow/ui/"   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"   xsi:schemaLocation="http://www.blizzard.com/wow/ui/">
	<Script file="SpeedrunSplits.lua"/>
		<Frame name="SpeedrunSplitsFrame" hidden="true">
			<Scripts>
				<OnLoad>
					SpeedrunSplits_OnLoad()
				</OnLoad>
				<OnEvent>
					SpeedrunSplits_OnEvent(event)
				</OnEvent>
			</Scripts>
		</Frame>
</Ui>
```


I also was getting on fresh client every time i escape:  "blizzard protected function" used by Blizzard_TimeManager (which is i think used in this addon)

![Wow_7jfCcqz9x5](https://user-images.githubusercontent.com/74269253/224709957-e59980ac-4506-4ecc-8ee7-7d4b6d8b5116.png)


Hope you can help me solve this. I don't know how to remove the .xml so that addon works to test if its a problem there.

**Comment by Sattva-108** [comment]
I also found this on official SpeedrunSplits change log
"tContains function" is present in Zarant backport, and it "could be breaking other addons"
https://www.curseforge.com/wow/addons/speedrunsplits/files/2757869

![firefox_D8keaiKUmT](https://user-images.githubusercontent.com/74269253/224743998-33e842a4-b78f-4773-bccc-b6cc9182e63f.png)

**Comment by RichSteini** [comment]
SpeedrunSplits addon has been updated and works now with WeakAuras. The problem was the public declaration of the tContains function that is used by WeakAuras too.
