### ISSUE TITLE
Wish to add Equipment Slot  --> Trinket 1 and Trinket 2

### ISSUE THREAD

**Issue by Sneften** [RichSteini/WeakAuras2-TBC-2.4.3#16]
Hey as the title reads,  if possible i would like the option to pick the trinket slots here: 
![image](https://user-images.githubusercontent.com/103856689/227254315-8487d707-05b6-486f-88c8-7c69a572d746.png)

**Comment by silmawien** [comment]
Here's a possible fix from my fork. The slot names with a _UNIQUE seems to be missing from 2.4.3
https://github.com/silmawien/WeakAuras2-TBC-2.4.3/commit/6d7bf093639776ba3bd50ee147b975d1fc700673

**Comment by RichSteini** [comment]
@silmawien i did not really have time to take look at it this week, but you can send me a pull request and i'll implement your fix, thanks.

**Comment by RichSteini** [comment]
I implemented and tested it thanks for the contribution. [Merge pull request](https://github.com/RichSteini/WeakAuras2-TBC-2.4.3/commit/f3f8d2b341df043d43e836fc7f043873412b1c00) https://github.com/RichSteini/WeakAuras2-TBC-2.4.3/pull/17 [from silmawien/main](https://github.com/RichSteini/WeakAuras2-TBC-2.4.3/commit/f3f8d2b341df043d43e836fc7f043873412b1c00)
