### ISSUE TITLE
The target debuff trigger cannot distinguish between its own and teammates'

### ISSUE THREAD

**Issue by jiaweigang** [RichSteini/WeakAuras2-TBC-2.4.3#19]
The target debuff trigger does not come from its own option

**Comment by RichSteini** [comment]
Added in [Reinstate Own Only and Is Stealable aura trigger options](https://github.com/RichSteini/WeakAuras2-TBC-2.4.3/commit/9854c94dd309e92e54408ece28b830ceb8340f12).
