### ISSUE TITLE
Trigger Spell Cooldown doesn't respect Show Global Cooldown, always shows the GCD

### ISSUE THREAD

**Issue by tomtko** [RichSteini/WeakAuras2-TBC-2.4.3#2]
Seems to always show the GCD regardless of what the setting is set to

**Comment by RichSteini** [comment]
This has been fixed yesterday evening, make sure to always pull the newest version before reporting. The TBC api does not have an option to get the GCD status therefore a GCD reference spell was added.

**Comment by RichSteini** [comment]
If it still persists, then you can report it again, but closing it for now since i got already a positive feedback that it works correctly. [Fix cooldown trigger GCD (add reference spell)](https://github.com/RichSteini/WeakAuras2-TBC-2.4.3/commit/170daa636ec3852ac24bad61c71a41a8dd672388)
