### ISSUE TITLE
This Addon causes Fatal Errors

### ISSUE THREAD

**Issue by cpevors** [RichSteini/WeakAuras2-TBC-2.4.3#24]
## Describe the bug
I have stripped my client of all other addons, and isolated that this addon alone is causing my 2.4.3 client to suffer "fatal errors" that cause my client to crash. 

I, regrettably, don't have a ton of information outside of the image below and the txt file attached. 

![image](https://github.com/RichSteini/WeakAuras2-TBC-2.4.3/assets/139099164/60c68955-cf1d-4852-b3be-692a74bb28e5)

[2023-09-29 21.54.11 Crash.txt](https://github.com/RichSteini/WeakAuras2-TBC-2.4.3/files/12773314/2023-09-29.21.54.11.Crash.txt)

### To Reproduce

This error crops up doing a variety of things. When I go to log in, when I attempt to exit the game world to the character screen, when I'm reloading my UI, when I am on the character screen and trying to go 'back' to the log-in screen, etc. 

**Which version of WeakAuras are you using?**
I am using the very latest release available from this repository. Downloaded 29 September 2023. 

### Additional Info

WeakAuras.lua, just in case: [WeakAuras.zip](https://github.com/RichSteini/WeakAuras2-TBC-2.4.3/files/12773332/WeakAuras.zip)

**Comment by RichSteini** [comment]
This usually happens when an addon tries to load a texture that cannot be read or something along that. It's not the addons itself, it is some weakaura you have installed. Try to remove all of the weakauras you have and figure out which one is causing the issue.

**Comment by cpevors** [comment]
I really appreciate your time and your response. I'm a bit at a loss, however. None of my WeakAuras are using non-default textures, fonts, or 'functions' (i.e. I've not used any custom lua). Still crashes reliably on UI reload or when I attempt to change characters.

I tried deleting them all, and even with zero WeakAuras, I still have issues.

**Comment by cpevors** [comment]
Disregard. Found my ONE offending Aura. Bastard! Haha.

Thanks for your grace!

**Comment by RichSteini** [comment]
Ok nice. Yea even if it uses a default texture from WeakAuras, there can be issues since not everything there was tested in depth. Stuff like this doesn't really get resolved unfortunately, because people can't or don't want to figure out what exactly causes it and also don't report it.
