### ISSUE TITLE
Memory error on border options

### ISSUE THREAD

**Issue by Foodlenz** [RichSteini/WeakAuras2-TBC-2.4.3#3]
## Describe the bug
I was in the process of creating a progress bar weak aura.
Added a border to it.
Then went to change the style of border. 
As I hovered down the list, the game crashes throwing the same error.

Closed WoW, re-opened, tried again. Same thing.

Just tried one more time, this time going from the bottom up. It seems to crash as it goes from **Drop Shadow** to anything else.

Disabled all addons except WA/Compatibility, same thing.

![image](https://user-images.githubusercontent.com/72258441/223332578-12de2c6f-050c-4b97-8121-e4f70120e758.png)

**Comment by RichSteini** [comment]
The drop shadow border texture seems to have an issue, hard to pin point what is wrong with it. I have removed it now and tested all other border options which appear to work fine.
