### ISSUE TITLE
Drag and Drop Error

### ISSUE THREAD

**Issue by Foodlenz** [RichSteini/WeakAuras2-TBC-2.4.3#4]
## Describe the bug
Attempting to re-order auras via drag and drop causes the following error.

![image](https://user-images.githubusercontent.com/72258441/223349478-50c9fd12-ca6f-4ca3-a4b0-be55a070e669.png)

Using the arrows to re-order works fine though.

**Comment by RichSteini** [comment]
Solved in [5556472](https://github.com/RichSteini/WeakAuras2-TBC-2.4.3/commit/5556472e78c17c63450500e089d40fd3d5213574). The first group has a bit of a weird behaviour when hovered on top, but can't get it better than this. Dragging and dropping within a group works well.
