### ISSUE TITLE
Trigger issue

### ISSUE THREAD

**Issue by RogezTheOne** [RichSteini/WeakAuras2-TBC-2.4.3#5]
Making a WA with the following trigger doesnt work right now:

Combat Log -> Spell -> Energize -> Source Unit: Player -> Power Type: Mana

Tried and tested with shamans water shield, both with importing an aura from old WA (prior to release of this one) and modifying it, aswell as making new one from scratch and neither of those work

**Comment by RichSteini** [comment]
Fixed in [Fix combat log spell energize powertype issue (parameters wrong)](https://github.com/RichSteini/WeakAuras2-TBC-2.4.3/commit/e2db92effdffc4d7baf80ea91fb72b1da3d657df). Parameters wrong format for the generic function.
