### ISSUE TITLE
[Shaman][Cooldown] Earth/Fire/Frost shock.

### ISSUE THREAD

**Issue by Sattva-108** [RichSteini/WeakAuras2-TBC-2.4.3#8]
## Describe the bug

Seems that WA 2 cannot read Earth/Fire/Frost shock CDs.
It always returns that spell is not on cooldown 

### To Reproduce

1. Create new Icon Weakaura
2. Make it in trigger: Spell - Action Usable - Type spell name Earth Shock.
3. Try and see if its going to disappear.

**Which version of WeakAuras are you using?**

I'm using 4.0.0

### Video of bug reproduce on Stormforge TBC PTR (tried on another server too, its same)

https://user-images.githubusercontent.com/74269253/224352240-8608fc17-8579-4085-8ea6-01f262d9144e.mp4

**Comment by RichSteini** [comment]
I cannot reproduce this, when i do exactly the same as you in the video then it works for me completely normal. Can you make sure you have the latest version installed, do a clean fresh install with saved variables deleted and check if it still happens?

https://user-images.githubusercontent.com/50737013/224360739-5f0df668-f678-4238-94ed-71e7b527eea7.mp4

**Comment by Sattva-108** [comment]
Solved, by removing SavedVariables.
